In [1]:
import pandas as pd

In [2]:
s1 = pd.Series([5,20,30,35,60],index=['a','b','c','d','e']);

In [3]:
s1

a     5
b    20
c    30
d    35
e    60
dtype: int64

In [10]:
s1[1:3]

b    20
c    30
dtype: int64

In [11]:
s1[:'c']

a     5
b    20
c    30
dtype: int64

In [12]:
import numpy as np

In [22]:
np.random.seed(1)
df1= pd.DataFrame(np.random.randint(10,50,[5,4]))
df1

    0   1   2   3
0  47  22  18  19
1  21  15  25  10
2  26  11  22  17
3  16  35  30  47
4  28  30  21  38

In [1]:
for index,value in df1['X'].item():
    print(f"{index} = {value}")

NameError: name 'df1' is not defined

In [23]:
np.random.seed(1)
df2= pd.DataFrame(np.random.randint(10,50,[5,4]),index = 'a b c d e'.split(),columns=list('WXYZ'))
df2

    W   X   Y   Z
a  47  22  18  19
b  21  15  25  10
c  26  11  22  17
d  16  35  30  47
e  28  30  21  38

In [24]:
df2.loc['b']

W    21
X    15
Y    25
Z    10
Name: b, dtype: int32

In [25]:
df2.iloc[1]

W    21
X    15
Y    25
Z    10
Name: b, dtype: int32

In [26]:
df2[['W','Z']]

    W   Z
a  47  19
b  21  10
c  26  17
d  16  47
e  28  38

In [28]:
df2.loc[['a','c'],['X','Y','Z']]

    X   Y   Z
a  22  18  19
c  11  22  17

In [29]:
df2.loc[['a','b']]

    W   X   Y   Z
a  47  22  18  19
b  21  15  25  10

In [31]:
for index, row in df2.iterrows():
    print(f"{index}: X = {row['X']}")

a: X = 22
b: X = 15
c: X = 11
d: X = 35
e: X = 30

In [32]:
for index, row in df2.iterrows():
    for col in df2.columns:
        print(row[col])

47
22
18
19
21
15
25
10
26
11
22
17
16
35
30
47
28
30
21
38

In [33]:
df2>20

       W      X      Y      Z
a   True   True  False  False
b   True  False   True  False
c   True  False   True  False
d  False   True   True   True
e   True   True   True   True

In [34]:
df2[df2>20]

      W     X     Y     Z
a  47.0  22.0   NaN   NaN
b  21.0   NaN  25.0   NaN
c  26.0   NaN  22.0   NaN
d   NaN  35.0  30.0  47.0
e  28.0  30.0  21.0  38.0

In [35]:
df2[df2.X>20]

    W   X   Y   Z
a  47  22  18  19
d  16  35  30  47
e  28  30  21  38

In [36]:
df = pd.read_csv('Sample - Superstore.csv',encoding = 'ISO-8859-1')
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [37]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [38]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [39]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [45]:
df[df['Ship Mode'] == 'First Class'].groupby('Region').sum()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Region,,,,,,,,,,,,,,,,,,,,
Central,1522232,CA-2016-117590CA-2016-117590CA-2016-118255CA-2...,12/8/201612/8/20163/11/20163/11/201612/9/20171...,12/10/201612/10/20163/13/20163/13/201612/11/20...,First ClassFirst ClassFirst ClassFirst ClassFi...,GH-14485GH-14485ON-18715ON-18715KB-16600KB-166...,Gene HaleGene HaleOdella NelsonOdella NelsonKe...,CorporateCorporateCorporateCorporateCorporateC...,United StatesUnited StatesUnited StatesUnited ...,RichardsonRichardsonEaganEaganHoustonHoustonHo...,TexasTexasMinnesotaMinnesotaTexasTexasTexasIll...,20026706,TEC-PH-10004977FUR-FU-10003664TEC-AC-10000171O...,TechnologyFurnitureTechnologyOffice SuppliesOf...,PhonesFurnishingsAccessoriesBindersBindersFurn...,GE 30524EE4Electrix Architect's Clamp-On Swing...,58746.9154,1156,79.42,3707.2672
East,2380262,CA-2016-111682CA-2016-111682CA-2016-111682CA-2...,6/17/20166/17/20166/17/20166/17/20166/17/20166...,6/18/20166/18/20166/18/20166/18/20166/18/20166...,First ClassFirst ClassFirst ClassFirst ClassFi...,TB-21055TB-21055TB-21055TB-21055TB-21055TB-210...,Ted ButterfieldTed ButterfieldTed ButterfieldT...,ConsumerConsumerConsumerConsumerConsumerConsum...,United StatesUnited StatesUnited StatesUnited ...,TroyTroyTroyTroyTroyTroyTroyWilmingtonWilmingt...,New YorkNew YorkNew YorkNew YorkNew YorkNew Yo...,9113090,OFF-ST-10000604OFF-PA-10001569FUR-CH-10003968O...,Office SuppliesOffice SuppliesFurnitureOffice ...,StoragePaperChairsPaperAccessoriesBindersArtFu...,Home/Office Personal File CartsXerox 232Novime...,113587.0530,1805,76.50,15732.0141
South,1178876,CA-2016-119823CA-2016-127208CA-2016-127208CA-2...,6/4/20166/12/20166/12/20164/15/20173/8/20173/8...,6/6/20166/15/20166/15/20164/17/20173/11/20173/...,First ClassFirst ClassFirst ClassFirst ClassFi...,KD-16270SC-20770SC-20770SH-20395VB-21745VB-217...,Karen DanielsStewart CarmichaelStewart Carmich...,ConsumerCorporateCorporateConsumerCorporateCor...,United StatesUnited StatesUnited StatesUnited ...,SpringfieldDecaturDecaturArlingtonColumbusColu...,VirginiaAlabamaAlabamaVirginiaGeorgiaGeorgiaFl...,7994947,OFF-PA-10000482OFF-AP-10002118OFF-BI-10002309O...,Office SuppliesOffice SuppliesOffice SuppliesO...,PaperAppliancesBindersArtAppliancesLabelsPaper...,Snap-A-Way Black Print Carbonless Ruled Speed ...,49332.5660,830,34.30,6892.3854
West,2417165,CA-2017-157833CA-2016-158834CA-2016-158834CA-2...,6/17/20173/13/20163/13/20165/31/20155/31/20155...,6/20/20173/16/20163/16/20166/2/20156/2/20156/2...,First ClassFirst ClassFirst ClassFirst ClassFi...,KD-16345TW-21025TW-21025SP-20650SP-20650SP-206...,Katherine DucichTamara WillinghamTamara Willin...,ConsumerHome OfficeHome OfficeCorporateCorpora...,United StatesUnited StatesUnited StatesUnited ...,San FranciscoScottsdaleScottsdaleSan JoseSan J...,CaliforniaArizonaArizonaCaliforniaCaliforniaCa...,47094768,OFF-BI-10001721OFF-AP-10000326TEC-PH-10001254O...,Office SuppliesOffice SuppliesTechnologyOffice...,BindersAppliancesPhonesPaperPaperStoragePaperT...,Trimflex Flexible Post BindersBelkin 7 Outlet ...,129761.8885,1902,62.95,22638.1732

In [48]:
df['Ship Mode'].nunique()

4

In [49]:
df['Ship Mode'].value_counts()

Ship Mode
Standard Class    5968
Second Class      1945
First Class       1538
Same Day           543
Name: count, dtype: int64

In [50]:
s1

a     5
b    20
c    30
d    35
e    60
dtype: int64

In [52]:
def fn(x):
    return x**2

In [53]:
s1.apply(fn)

a      25
b     400
c     900
d    1225
e    3600
dtype: int64

In [55]:
s1.apply(lambda x : x**2)

a      25
b     400
c     900
d    1225
e    3600
dtype: int64

In [56]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [62]:
df[df['Product Name'].apply(lambda x : 'deluxe' in x.lower())]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.940,3,0.0,219.5820
23,24,US-2017-156909,7/16/2017,7/18/2017,Second Class,SF-20065,Sandra Flanagan,Consumer,United States,Philadelphia,...,19140,East,FUR-CH-10002774,Furniture,Chairs,"Global Deluxe Stacking Chair, Gray",71.372,2,0.3,-1.0196
124,125,US-2014-152030,12/26/2014,12/28/2014,Second Class,AD-10180,Alan Dominguez,Home Office,United States,Houston,...,77041,Central,FUR-CH-10004063,Furniture,Chairs,Global Deluxe High-Back Manager's Chair,600.558,3,0.3,-8.5794
149,150,CA-2016-114489,12/5/2016,12/9/2016,Standard Class,JE-16165,Justin Ellison,Corporate,United States,Franklin,...,53132,Central,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",1951.840,8,0.0,585.5520
157,158,CA-2014-104269,3/1/2014,3/6/2014,Second Class,DB-13060,Dave Brooks,Consumer,United States,Seattle,...,98115,West,FUR-CH-10004063,Furniture,Chairs,Global Deluxe High-Back Manager's Chair,457.568,2,0.2,51.4764
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9310,9311,US-2016-102141,8/26/2016,8/31/2016,Standard Class,KD-16615,Ken Dana,Corporate,United States,New York City,...,10024,East,OFF-BI-10001510,Office Supplies,Binders,Deluxe Heavy-Duty Vinyl Round Ring Binder,146.688,8,0.2,45.8400
9351,9352,CA-2016-159009,9/23/2016,9/27/2016,Standard Class,DP-13105,Dave Poirier,Corporate,United States,Seattle,...,98115,West,FUR-CH-10003396,Furniture,Chairs,Global Deluxe Steno Chair,184.752,3,0.2,-20.7846
9645,9646,US-2017-107979,6/8/2017,6/13/2017,Standard Class,FO-14305,Frank Olsen,Consumer,United States,Glendale,...,85301,West,OFF-ST-10002485,Office Supplies,Storage,Rogers Deluxe File Chest,35.168,2,0.2,-8.3524
9788,9789,CA-2017-144491,3/27/2017,4/1/2017,Standard Class,CJ-12010,Caroline Jumper,Consumer,United States,Houston,...,77070,Central,FUR-CH-10004063,Furniture,Chairs,Global Deluxe High-Back Manager's Chair,600.558,3,0.3,-8.5794
9792,9793,CA-2014-127166,5/21/2014,5/23/2014,Second Class,KH-16360,Katherine Hughes,Consumer,United States,Houston,...,77070,Central,FUR-CH-10003396,Furniture,Chairs,Global Deluxe Steno Chair,107.772,2,0.3,-29.2524

In [63]:
df[df['Product Name'].apply(lambda x : 'deluxe' in x.lower())] ['Product Name'].unique()

array(['Hon Deluxe Fabric Upholstered Stacking Chairs, Rounded Back',
       'Global Deluxe Stacking Chair, Gray',
       "Global Deluxe High-Back Manager's Chair",
       'Rogers Deluxe File Chest', 'Global Deluxe Office Fabric Chairs',
       'Global Deluxe Steno Chair',
       'Boston 1645 Deluxe Heavier-Duty Electric Pencil Sharpener',
       'Deluxe Rollaway Locking File with Drawer',
       'Deluxe Chalkboard Eraser Cleaner',
       'Deluxe Heavy-Duty Vinyl Round Ring Binder',
       'Hon Deluxe Fabric Upholstered Stacking Chairs',
       'Global Deluxe High-Back Office Chair in Storm',
       'Hon Deluxe Fabric Upholstered Stacking Chairs, Squared Back'],
      dtype=object)

In [64]:
df.tail(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9984,9985,CA-2015-100251,5/17/2015,5/23/2015,Standard Class,DV-13465,Dianna Vittorini,Consumer,United States,Long Beach,...,11561,East,OFF-LA-10003766,Office Supplies,Labels,Self-Adhesive Removable Labels,31.500,10,0.0,15.1200
9985,9986,CA-2015-100251,5/17/2015,5/23/2015,Standard Class,DV-13465,Dianna Vittorini,Consumer,United States,Long Beach,...,11561,East,OFF-SU-10000898,Office Supplies,Supplies,Acme Hot Forged Carbon Steel Scissors with Nic...,55.600,4,0.0,16.1240
9986,9987,CA-2016-125794,9/29/2016,10/3/2016,Standard Class,ML-17410,Maris LaWare,Consumer,United States,Los Angeles,...,90008,West,TEC-AC-10003399,Technology,Accessories,Memorex Mini Travel Drive 64 GB USB 2.0 Flash ...,36.240,1,0.0,15.2208
9987,9988,CA-2017-163629,11/17/2017,11/21/2017,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,Athens,...,30605,South,TEC-AC-10001539,Technology,Accessories,Logitech G430 Surround Sound Gaming Headset wi...,79.990,1,0.0,28.7964
9988,9989,CA-2017-163629,11/17/2017,11/21/2017,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,Athens,...,30605,South,TEC-PH-10004006,Technology,Phones,Panasonic KX - TS880B Telephone,206.100,5,0.0,55.6470
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.248,3,0.2,4.1028
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,0.0,15.6332
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0.0,13.3200
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480

In [65]:
df.head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
5,6,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694
6,7,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.2800,4,0.00,1.9656
7,8,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
8,9,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.5040,3,0.20,5.7825
9,10,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,5,0.00,34.4700

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [76]:
df.['Profit'].sort_values()

SyntaxError: invalid syntax (3982624263.py, line 1)