In [1]:
import pandas as pd
import numpy as np

In [2]:
np.random.seed(1)
df = pd.DataFrame(np.random.randint(1,100,[5,4])
                  ,index='a b c d e'.split()
                  ,columns= 'W X Y Z'.split())
df

    W   X   Y   Z
a  38  13  73  10
b  76   6  80  65
c  17   2  77  72
d   7  26  51  21
e  19  85  12  29

In [3]:
'''indert new value'''

'indert new value'

In [4]:
df['I'] = [1,2,3,4,5]
df

    W   X   Y   Z  I
a  38  13  73  10  1
b  76   6  80  65  2
c  17   2  77  72  3
d   7  26  51  21  4
e  19  85  12  29  5

In [5]:
len(df.index)

5

In [6]:
df['J'] = np.zeros(len(df.index))
df

    W   X   Y   Z  I    J
a  38  13  73  10  1  0.0
b  76   6  80  65  2  0.0
c  17   2  77  72  3  0.0
d   7  26  51  21  4  0.0
e  19  85  12  29  5  0.0

In [7]:
df['SUM'] = df['W'] + df['X']
df

    W   X   Y   Z  I    J  SUM
a  38  13  73  10  1  0.0   51
b  76   6  80  65  2  0.0   82
c  17   2  77  72  3  0.0   19
d   7  26  51  21  4  0.0   33
e  19  85  12  29  5  0.0  104

In [8]:
df['J'] = [3,3,3,3,3]
df

    W   X   Y   Z  I  J  SUM
a  38  13  73  10  1  3   51
b  76   6  80  65  2  3   82
c  17   2  77  72  3  3   19
d   7  26  51  21  4  3   33
e  19  85  12  29  5  3  104

In [9]:
df['W2X'] = df['W']**2 - df['X']
df

    W   X   Y   Z  I  J  SUM   W2X
a  38  13  73  10  1  3   51  1431
b  76   6  80  65  2  3   82  5770
c  17   2  77  72  3  3   19   287
d   7  26  51  21  4  3   33    23
e  19  85  12  29  5  3  104   276

In [10]:
df.drop('W2X',axis=1)

    W   X   Y   Z  I  J  SUM
a  38  13  73  10  1  3   51
b  76   6  80  65  2  3   82
c  17   2  77  72  3  3   19
d   7  26  51  21  4  3   33
e  19  85  12  29  5  3  104

In [11]:
df.drop('I',axis=1,inplace = True)
df

    W   X   Y   Z  J  SUM   W2X
a  38  13  73  10  3   51  1431
b  76   6  80  65  3   82  5770
c  17   2  77  72  3   19   287
d   7  26  51  21  3   33    23
e  19  85  12  29  3  104   276

In [12]:
df.drop('J',axis=1,inplace = True)
df

    W   X   Y   Z  SUM   W2X
a  38  13  73  10   51  1431
b  76   6  80  65   82  5770
c  17   2  77  72   19   287
d   7  26  51  21   33    23
e  19  85  12  29  104   276

In [13]:
df.drop('SUM',axis=1,inplace = True)
df

    W   X   Y   Z   W2X
a  38  13  73  10  1431
b  76   6  80  65  5770
c  17   2  77  72   287
d   7  26  51  21    23
e  19  85  12  29   276

In [14]:
df.drop('W2X',axis=1,inplace = True)
df

    W   X   Y   Z
a  38  13  73  10
b  76   6  80  65
c  17   2  77  72
d   7  26  51  21
e  19  85  12  29

In [15]:
df.loc[['a','b'],'X':'Z'] = [[1,2,3],[4,5,6]]
df

C:\Users\Asus\AppData\Local\Temp\ipykernel_7612\899418700.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[1, 4]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  df.loc[['a','b'],'X':'Z'] = [[1,2,3],[4,5,6]]
C:\Users\Asus\AppData\Local\Temp\ipykernel_7612\899418700.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[2, 5]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  df.loc[['a','b'],'X':'Z'] = [[1,2,3],[4,5,6]]
C:\Users\Asus\AppData\Local\Temp\ipykernel_7612\899418700.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[3, 6]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  df.loc[['a','b'],'X':'Z'] = [[1,2,3],[4,5,6]]

    W   X   Y   Z
a  38   1   2   3
b  76   4   5   6
c  17   2  77  72
d   7  26  51  21
e  19  85  12  29

In [16]:
df.rename(columns={'W':'pi','X':'rad'},inplace=True)
df

   pi  rad   Y   Z
a  38    1   2   3
b  76    4   5   6
c  17    2  77  72
d   7   26  51  21
e  19   85  12  29

In [17]:
df.reset_index(inplace= True)
df

  index  pi  rad   Y   Z
0     a  38    1   2   3
1     b  76    4   5   6
2     c  17    2  77  72
3     d   7   26  51  21
4     e  19   85  12  29

In [18]:
df.loc[3]

index     d
pi        7
rad      26
Y        51
Z        21
Name: 3, dtype: object

In [19]:
df.set_index('index',inplace=True)
df

       pi  rad   Y   Z
index
a      38    1   2   3
b      76    4   5   6
c      17    2  77  72
d       7   26  51  21
e      19   85  12  29

In [20]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
'A': ['A0', 'A1', 'A2', 'A3'],
'B': ['B0', 'B1', 'B2', 'B3']}
                    ,index = [0,1,2,4])
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
'C': ['C0', 'C1', 'C2', 'C3'],
'D': ['D0', 'D1', 'D2', 'D3']})

In [21]:
left

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
4  K3  A3  B3

In [22]:
right

  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [23]:
display(left,right,df)

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
4  K3  A3  B3

  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

       pi  rad   Y   Z
index
a      38    1   2   3
b      76    4   5   6
c      17    2  77  72
d       7   26  51  21
e      19   85  12  29

In [24]:
pd.concat([left,right],axis=1)

   key    A    B  key    C    D
0   K0   A0   B0   K0   C0   D0
1   K1   A1   B1   K1   C1   D1
2   K2   A2   B2   K2   C2   D2
4   K3   A3   B3  NaN  NaN  NaN
3  NaN  NaN  NaN   K3   C3   D3

In [25]:
d = {
    'A':[1,2,np.nan,3],
    'B':[5,np.nan,np.nan,np.nan],
    'C':[1,2,3,4]
}
df = pd.DataFrame(d)
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3
3  3.0  NaN  4

In [26]:
df.dropna(thresh=2,axis=1)

     A  C
0  1.0  1
1  2.0  2
2  NaN  3
3  3.0  4

In [27]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3
3  3.0  NaN  4

In [28]:
df[df['A'].isnull()]

    A   B  C
2 NaN NaN  3

In [29]:
df['A'].isnull()

0    False
1    False
2     True
3    False
Name: A, dtype: bool

In [30]:
sum(df['A'].isnull())

1

In [31]:
df[df['B'].isnull()]

     A   B  C
1  2.0 NaN  2
2  NaN NaN  3
3  3.0 NaN  4

In [32]:
df.fillna(value= df['A'].mean())

     A    B  C
0  1.0  5.0  1
1  2.0  2.0  2
2  2.0  2.0  3
3  3.0  2.0  4

In [33]:
df['A'].fillna(value =df['A'].mean())

0    1.0
1    2.0
2    2.0
3    3.0
Name: A, dtype: float64

In [34]:
df.fillna({'A':df['A'].mean(),'B':0})

     A    B  C
0  1.0  5.0  1
1  2.0  0.0  2
2  2.0  0.0  3
3  3.0  0.0  4