#  Data Preparation Exercise 

แบบฝึกหัดนี้เป็นแบบฝึกหัดทดสอบทักษะการเตรียมข้อมูล โดยให้ทำตามคำสั่ง ต่อไปนี้

---

**Import pandas and numpy**

In [1]:
import pandas as pd
import numpy as np

**1. ให้นำข้อมูลจาก Salaries.csv มาตรวจสอบว่าใครบ้างที่ทำงานเป็นตำรวจ แล้วสร้างไฟล์ .csv เก็บข้อมูลไว้**

In [2]:
sal = pd.read_csv('Salaries.csv',encoding = 'ISO-8859-1')

In [3]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB

In [4]:
sal[sal['JobTitle'].apply(lambda x : 'POLICE DEPARTMENT' in x.upper())]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
11,12,PATRICIA JACKSON,CAPTAIN III (POLICE DEPARTMENT),99722.00,87082.62,110804.30,NaN,297608.92,297608.92,2011,NaN,San Francisco,NaN
15,16,RICHARD CORRIEA,"COMMANDER III, (POLICE DEPARTMENT)",198778.01,73478.20,13957.65,NaN,286213.86,286213.86,2011,NaN,San Francisco,NaN
28,29,DENISE SCHMITT,DEPUTY CHIEF III (POLICE DEPARTMENT),261717.60,0.00,2357.00,NaN,264074.60,264074.60,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
113903,113904,Theresa J San Giacomo,"Sergeant, (Police Department)",130260.00,9230.90,11258.04,41477.75,150748.94,192226.69,2014,NaN,San Francisco,NaN
113934,113935,Ricardo S Castillo,"Sergeant, (Police Department)",130260.01,10232.14,9797.38,41646.26,150289.53,191935.79,2014,NaN,San Francisco,NaN
114281,114282,Alan M Callaway,"Sergeant, (Police Department)",130260.07,4013.90,11554.05,41687.89,145828.02,187515.91,2014,NaN,San Francisco,NaN
114331,114332,Paris C Deshong,Lieutenant (Police Department),137370.19,379.66,6232.79,42931.34,143982.64,186913.98,2014,NaN,San Francisco,NaN
123438,123439,John A Haggett,"Sergeant, (Police Department)",16032.00,0.00,104018.22,5179.89,120050.22,125230.11,2014,NaN,San Francisco,NaN

In [5]:
police_df = sal[sal['JobTitle'].apply(lambda x : 'POLICE DEPARTMENT' in x.upper())]

In [6]:
police_df.to_csv("Police_Salaries.csv", index=False)

In [7]:
Read_Police = pd.read_csv('Police_Salaries.csv',encoding = 'ISO-8859-1')

In [8]:
Read_Police

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
1,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
2,12,PATRICIA JACKSON,CAPTAIN III (POLICE DEPARTMENT),99722.00,87082.62,110804.30,NaN,297608.92,297608.92,2011,NaN,San Francisco,NaN
3,16,RICHARD CORRIEA,"COMMANDER III, (POLICE DEPARTMENT)",198778.01,73478.20,13957.65,NaN,286213.86,286213.86,2011,NaN,San Francisco,NaN
4,29,DENISE SCHMITT,DEPUTY CHIEF III (POLICE DEPARTMENT),261717.60,0.00,2357.00,NaN,264074.60,264074.60,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
707,113904,Theresa J San Giacomo,"Sergeant, (Police Department)",130260.00,9230.90,11258.04,41477.75,150748.94,192226.69,2014,NaN,San Francisco,NaN
708,113935,Ricardo S Castillo,"Sergeant, (Police Department)",130260.01,10232.14,9797.38,41646.26,150289.53,191935.79,2014,NaN,San Francisco,NaN
709,114282,Alan M Callaway,"Sergeant, (Police Department)",130260.07,4013.90,11554.05,41687.89,145828.02,187515.91,2014,NaN,San Francisco,NaN
710,114332,Paris C Deshong,Lieutenant (Police Department),137370.19,379.66,6232.79,42931.34,143982.64,186913.98,2014,NaN,San Francisco,NaN
711,123439,John A Haggett,"Sergeant, (Police Department)",16032.00,0.00,104018.22,5179.89,120050.22,125230.11,2014,NaN,San Francisco,NaN

**2. ให้นำข้อมูลจาก sale_quarterly1.xlsx มาสร้าง Pivot Table เพื่อแสดง ยอดขายเฉลี่ยของพนักงานในแต่ละควอเตอร์**

In [9]:
sale_exc = pd.read_excel('sale_quarterly1.xlsx',usecols='b:e',header = 2)

In [10]:
sale_exc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Employee  20 non-null     object
 1   Sales     20 non-null     int64
 2   Quarter   20 non-null     int64
 3   Country   20 non-null     object
dtypes: int64(2), object(2)
memory usage: 772.0+ bytes

In [11]:
sale_exc.head()

     Employee  Sales  Quarter  Country
0       ณิแนน   1000        1       US
1  กอบเกียรติ    300        1  ญี่ปุ่น
2        Tina    400        1      ไทย
3       Maria    500        1       UK
4        Bill    800        1       US

In [12]:
sale_exc.pivot_table(index='Employee',columns='Quarter',values='Sales',aggfunc='mean')

Quarter          1       2       3       4
Employee
Bill         800.0    60.0   300.0    50.0
Maria        500.0    50.0   200.0   750.0
Tina         400.0   700.0   750.0   250.0
กอบเกียรติ   300.0   500.0   900.0   900.0
ณิแนน       1000.0  1000.0  1000.0  1000.0

**3. ให้นำข้อมูลจาก data_clean_bfclean.csv คอลัมน์ SQ_M มาจัดการ**

โดยที่
- ข้อมูลที่มีค่าน้อยกว่า 100 ถือว่าเป็นข้อมูลที่ผิดพลาด ให้เปลี่ยนเป็น Null
- ข้อมูลที่ไม่ใช่ตัวเลขถือเป็นข้อมูลที่ผิดพลาด ให้เปลี่ยนเป็น Null
- ทำคอลัมน์ให้เป็น float64

In [13]:
data_clean = pd.read_csv('data_clean_bfclean.csv')

In [14]:
data_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PID           11 non-null     object
 1   ST_NUM        8 non-null      float64
 2   ST_NAME       11 non-null     object
 3   OWN_OCCUPIED  10 non-null     object
 4   NUM_BEDROOMS  10 non-null     float64
 5   NUM_BATH      11 non-null     object
 6   SQ_M          10 non-null     object
dtypes: float64(2), object(5)
memory usage: 748.0+ bytes

In [15]:
data_clean.head()

     PID  ST_NUM ST_NAME OWN_OCCUPIED  NUM_BEDROOMS NUM_BATH   SQ_M
0    กอบ   104.0  PUTNAM            Y           3.0        1   1000
1    แนน   197.0   LETON            n           3.0        1     --
2    Lam     NaN   LETON            N           NaN        1    850
3  Ninan   201.0   BEREY            N           1.0       -2  700.5
4    Nii     NaN   BEREY            Y           2.0     2ABC   1600

In [16]:
def fn(x):
    try:
        x = float(x)
        if x < 100:
            return None
        else:
            return x
    except:
        return None
        
data_clean['SQ_M'] = data_clean['SQ_M'].apply(fn).astype('float64',errors= 'ignore')

In [17]:
data_clean.head()

     PID  ST_NUM ST_NAME OWN_OCCUPIED  NUM_BEDROOMS NUM_BATH    SQ_M
0    กอบ   104.0  PUTNAM            Y           3.0        1  1000.0
1    แนน   197.0   LETON            n           3.0        1     NaN
2    Lam     NaN   LETON            N           NaN        1   850.0
3  Ninan   201.0   BEREY            N           1.0       -2   700.5
4    Nii     NaN   BEREY            Y           2.0     2ABC  1600.0

In [18]:
data_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PID           11 non-null     object
 1   ST_NUM        8 non-null      float64
 2   ST_NAME       11 non-null     object
 3   OWN_OCCUPIED  10 non-null     object
 4   NUM_BEDROOMS  10 non-null     float64
 5   NUM_BATH      11 non-null     object
 6   SQ_M          7 non-null      float64
dtypes: float64(3), object(4)
memory usage: 748.0+ bytes